version: '3.8'

services:

 shoshoppers:
  image: shindqq/shoppers_app
  restart: unless-stopped
  container_name: shoshoppers_compose_container
  build:
   context: .
   dockerfile: ShoShoppers.API/Dockerfile
  environment: 
  - ASPNETCORE_URLS:http://*:5003;https://*:5002;http://*:3000
  ports:
  - "3000:80" 
  - "5003:5003" 
  - "5002:80"
 nginx:
  restart: unless-stopped
  container_name: nginx_compose_container
  build:
   context: .
   dockerfile: nginx/nginx.Dockerfile
  depends_on:
   - shoshoppers
  ports:
   - "80:8080"
   - "443:4430"
  volumes:
   - ./nginx/conf/:/etc/nginx/conf.d/:ro
   - ./certbot/www:/var/www/certbot/:ro
   - ./certbot/conf/:/etc/nginx/ssl/:ro
 certbot:
  image: certbot/certbot:arm64v8-v1.3.0
  volumes:
   - ./certbot/www/:/var/www/certbot/:rw
   - ./certbot/conf/:/etc/letsencrypt/:rw
  command: certonly --webroot -w /var/www/certbot --force-renewal --email denis110402@gmail.com --non-interactive -d shoshoppers.works --agree-tos
 mysql:
  image: mysql
  restart: unless-stopped
  container_name: mysql_compose-server
  environment:
   MYSQL_DATABASE: 'ShoShopers'
   MYSQL_USER: 'Shind'
   MYSQL_PASSWORD: 'VaUMdqnW2TwkZJ34ZxkXNHepWIq3kAHKxvYCxNygPZRVHcIrBy2bMxIzth'
   MYSQL_ROOT_PASSWORD: 'VaUMdqnW2TwkZJ34ZxkXNHepWIq3kAHKxvYCxNygPZRVHcIrBy2bMxIzth'
  ports:
   - '3306:3306'
  expose:
   - '3306'
  volumes:
  - shoshoppersdb:/var/lib/mysql

volumes:
  shoshoppersdb: